const BASE_URL = 'https://www.rottentomatoes.com'
const MAX_REVIEWS_PER_PAGE = 20
const MAX_VISITABLE_PAGE = 51
const MAX_TOTAL_REVIEWS = MAX_VISITABLE_PAGE * MAX_REVIEWS_PER_PAGE

module.exports = {
  BASE_URL,
  MAX_REVIEWS_PER_PAGE,
  MAX_VISITABLE_PAGE,
  MAX_TOTAL_REVIEWS,
}
